Add some resources to data collector instead of empty run
jeremiahsnapp/chef-load pull request #7
Opened 2017-06-13 17:38 UTC by danielsdeleo

Adds a hardcoded set of 10 updated resources to the data collector request. Ideally this would be a lot larger and configurable, but for now it's an improvement over just sending empty run data.

Signed-off-by: Daniel DeLeo <dan@chef.io>

2017-06-14 14:45 UTC, jeremiahsnapp requested changes

2017-06-14 14:45 UTC, jeremiahsnapp commented on data-collector.go
> +`
The list's closing bracket `]` is missing. Please add that and indent the resources.

2017-06-14 22:34 UTC, danielsdeleo commented
derp, already changed that but forgot to commit it. done.

2017-06-22 15:18 UTC, jeremiahsnapp commented
Thanks @danielsdeleo for pointing in the right direction. As of 0.5.0 you can now use the `converge_status_json_file` and `compliance_status_json_file` options to apply sample data to the API requests so I'll close this PR.

https://github.com/jeremiahsnapp/chef-load#using-sample-json-data-files

2017-06-22 15:18 UTC, closed without merging

2017-06-22 20:41 UTC, danielsdeleo commented
Cool, that's a better implementation anyway, I was just doing what was expedient for me at the time. 👍